# Taken from the Cropland Class Table https://developers.google.com/earth-engine/datasets/catalog/USDA_NASS_CDL#bands

class_info = [
    {"Value": 0, "Color": "#000000", "Description": "Other"},
    {"Value": 1, "Color": "#ffd300", "Description": "Corn"},
    {"Value": 2, "Color": "#ff2626", "Description": "Cotton"},
    {"Value": 3, "Color": "#00a8e2", "Description": "Rice"},
    {"Value": 4, "Color": "#ff9e0a", "Description": "Sorghum"},
    {"Value": 5, "Color": "#267000", "Description": "Soybeans"},
    {"Value": 6, "Color": "#ffff00", "Description": "Sunflower"},
    {"Value": 10, "Color": "#70a500", "Description": "Peanuts"},
    {"Value": 11, "Color": "#00af49", "Description": "Tobacco"},
    {"Value": 12, "Color": "#dda50a", "Description": "Sweet Corn"},
    {"Value": 13, "Color": "#dda50a", "Description": "Pop or Orn Corn"},
    {"Value": 14, "Color": "#7cd3ff", "Description": "Mint"},
    {"Value": 21, "Color": "#e2007c", "Description": "Barley"},
    {"Value": 22, "Color": "#896054", "Description": "Durum Wheat"},
    {"Value": 23, "Color": "#d8b56b", "Description": "Spring Wheat"},
    {"Value": 24, "Color": "#a57000", "Description": "Winter Wheat"},
    {"Value": 25, "Color": "#d69ebc", "Description": "Other Small Grains"},
    {"Value": 26, "Color": "#707000", "Description": "Dbl Crop WinWht/Soybeans"},
    {"Value": 27, "Color": "#aa007c", "Description": "Rye"},
    {"Value": 28, "Color": "#a05989", "Description": "Oats"},
    {"Value": 29, "Color": "#700049", "Description": "Millet"},
    {"Value": 30, "Color": "#d69ebc", "Description": "Speltz"},
    {"Value": 31, "Color": "#d1ff00", "Description": "Canola"},
    {"Value": 32, "Color": "#7c99ff", "Description": "Flaxseed"},
    {"Value": 33, "Color": "#d6d600", "Description": "Safflower"},
    {"Value": 34, "Color": "#d1ff00", "Description": "Rape Seed"},
    {"Value": 35, "Color": "#00af49", "Description": "Mustard"},
    {"Value": 36, "Color": "#ffa5e2", "Description": "Alfalfa"},
    {"Value": 37, "Color": "#a5f28c", "Description": "Other Hay/Non Alfalfa"},
    {"Value": 38, "Color": "#00af49", "Description": "Camelina"},
    {"Value": 39, "Color": "#d69ebc", "Description": "Buckwheat"},
    {"Value": 41, "Color": "#a800e2", "Description": "Sugarbeets"},
    {"Value": 42, "Color": "#a50000", "Description": "Dry Beans"},
    {"Value": 43, "Color": "#702600", "Description": "Potatoes"},
    {"Value": 44, "Color": "#00af49", "Description": "Other Crops"},
    {"Value": 45, "Color": "#af7cff", "Description": "Sugarcane"},
    {"Value": 46, "Color": "#702600", "Description": "Sweet Potatoes"},
    {"Value": 47, "Color": "#ff6666", "Description": "Misc Vegs & Fruits"},
    {"Value": 48, "Color": "#ff6666", "Description": "Watermelons"},
    {"Value": 49, "Color": "#ffcc66", "Description": "Onions"},
    {"Value": 50, "Color": "#ff6666", "Description": "Cucumbers"},
    {"Value": 51, "Color": "#00af49", "Description": "Chick Peas"},
    {"Value": 52, "Color": "#00ddaf", "Description": "Lentils"},
    {"Value": 53, "Color": "#54ff00", "Description": "Peas"},
    {"Value": 54, "Color": "#f2a377", "Description": "Tomatoes"},
    {"Value": 55, "Color": "#ff6666", "Description": "Caneberries"},
    {"Value": 56, "Color": "#00af49", "Description": "Hops"},
    {"Value": 57, "Color": "#7cd3ff", "Description": "Herbs"},
    {"Value": 58, "Color": "#e8bfff", "Description": "Clover/Wildflowers"},
    {"Value": 59, "Color": "#afffdd", "Description": "Sod/Grass Seed"},
    {"Value": 60, "Color": "#00af49", "Description": "Switchgrass"},
    {"Value": 61, "Color": "#bfbf77", "Description": "Fallow/Idle Cropland"},
    {"Value": 63, "Color": "#93cc93", "Description": "Forest"},
    {"Value": 64, "Color": "#c6d69e", "Description": "Shrubland"},
    {"Value": 65, "Color": "#ccbfa3", "Description": "Barren"},
    {"Value": 66, "Color": "#ff00ff", "Description": "Cherries"},
    {"Value": 67, "Color": "#ff8eaa", "Description": "Peaches"},
    {"Value": 68, "Color": "#ba004f", "Description": "Apples"},
    {"Value": 69, "Color": "#704489", "Description": "Grapes"},
    {"Value": 70, "Color": "#007777", "Description": "Christmas Trees"},
    {"Value": 71, "Color": "#af9970", "Description": "Other Tree Crops"},
    {"Value": 72, "Color": "#ffff7c", "Description": "Citrus"},
    {"Value": 74, "Color": "#b5705b", "Description": "Pecans"},
    {"Value": 75, "Color": "#00a582", "Description": "Almonds"},
    {"Value": 76, "Color": "#e8d6af", "Description": "Walnuts"},
    {"Value": 77, "Color": "#af9970", "Description": "Pears"},
    {"Value": 81, "Color": "#f2f2f2", "Description": "Clouds/No Data"},
    {"Value": 82, "Color": "#999999", "Description": "Developed"},
    {"Value": 83, "Color": "#4970a3", "Description": "Water"},
    {"Value": 87, "Color": "#7cafaf", "Description": "Wetlands"},
    {"Value": 88, "Color": "#e8ffbf", "Description": "Nonag/Undefined"},
    {"Value": 92, "Color": "#00ffff", "Description": "Aquaculture"},
    {"Value": 111, "Color": "#4970a3", "Description": "Open Water"},
    {"Value": 112, "Color": "#d3e2f9", "Description": "Perennial Ice/Snow"},
    {"Value": 121, "Color": "#999999", "Description": "Developed/Open Space"},
    {"Value": 122, "Color": "#999999", "Description": "Developed/Low Intensity"},
    {"Value": 123, "Color": "#999999", "Description": "Developed/Med Intensity"},
    {"Value": 124, "Color": "#999999", "Description": "Developed/High Intensity"},
    {"Value": 131, "Color": "#ccbfa3", "Description": "Barren"},
    {"Value": 141, "Color": "#93cc93", "Description": "Deciduous Forest"},
    {"Value": 142, "Color": "#93cc93", "Description": "Evergreen Forest"},
    {"Value": 143, "Color": "#93cc93", "Description": "Mixed Forest"},
    {"Value": 152, "Color": "#c6d69e", "Description": "Shrubland"},
    {"Value": 176, "Color": "#e8ffbf", "Description": "Grassland/Pasture"},
    {"Value": 190, "Color": "#7cafaf", "Description": "Woody Wetlands"},
    {"Value": 195, "Color": "#7cafaf", "Description": "Herbaceous Wetlands"},
    {"Value": 204, "Color": "#00ff8c", "Description": "Pistachios"},
    {"Value": 205, "Color": "#d69ebc", "Description": "Triticale"},
    {"Value": 206, "Color": "#ff6666", "Description": "Carrots"},
    {"Value": 207, "Color": "#ff6666", "Description": "Asparagus"},
    {"Value": 208, "Color": "#ff6666", "Description": "Garlic"},
    {"Value": 209, "Color": "#ff6666", "Description": "Cantaloupes"},
    {"Value": 210, "Color": "#ff8eaa", "Description": "Prunes"},
    {"Value": 211, "Color": "#334933", "Description": "Olives"},
    {"Value": 212, "Color": "#e27026", "Description": "Oranges"},
    {"Value": 213, "Color": "#ff6666", "Description": "Honeydew Melons"},
    {"Value": 214, "Color": "#ff6666", "Description": "Broccoli"},
    {"Value": 215, "Color": "#739755", "Description": "Avocados"},
    {"Value": 216, "Color": "#ff6666", "Description": "Peppers"},
    {"Value": 217, "Color": "#af9970", "Description": "Pomegranates"},
    {"Value": 218, "Color": "#ff8eaa", "Description": "Nectarines"},
    {"Value": 219, "Color": "#ff6666", "Description": "Greens"},
    {"Value": 220, "Color": "#ff8eaa", "Description": "Plums"},
    {"Value": 221, "Color": "#ff6666", "Description": "Strawberries"},
    {"Value": 222, "Color": "#ff6666", "Description": "Squash"},
    {"Value": 223, "Color": "#ff8eaa", "Description": "Apricots"},
    {"Value": 224, "Color": "#00af49", "Description": "Vetch"},
    {"Value": 225, "Color": "#ffd300", "Description": "Dbl Crop WinWht/Corn"},
    {"Value": 226, "Color": "#ffd300", "Description": "Dbl Crop Oats/Corn"},
    {"Value": 227, "Color": "#ff6666", "Description": "Lettuce"},
    {"Value": 228, "Color": "#f8d248", "Description": "Dbl Crop Triticale/Corn"},
    {"Value": 229, "Color": "#ff6666", "Description": "Pumpkins"},
    {"Value": 230, "Color": "#896054", "Description": "Dbl Crop Lettuce/Durum Wht"},
    {"Value": 231, "Color": "#ff6666", "Description": "Dbl Crop Lettuce/Cantaloupe"},
    {"Value": 232, "Color": "#ff2626", "Description": "Dbl Crop Lettuce/Cotton"},
    {"Value": 233, "Color": "#e2007c", "Description": "Dbl Crop Lettuce/Barley"},
    {"Value": 234, "Color": "#ff9e0a", "Description": "Dbl Crop Durum Wht/Sorghum"},
    {"Value": 235, "Color": "#ff9e0a", "Description": "Dbl Crop Barley/Sorghum"},
    {"Value": 236, "Color": "#a57000", "Description": "Dbl Crop WinWht/Sorghum"},
    {"Value": 237, "Color": "#ffd300", "Description": "Dbl Crop Barley/Corn"},
    {"Value": 238, "Color": "#a57000", "Description": "Dbl Crop WinWht/Cotton"},
    {"Value": 239, "Color": "#267000", "Description": "Dbl Crop Soybeans/Cotton"},
    {"Value": 240, "Color": "#267000", "Description": "Dbl Crop Soybeans/Oats"},
    {"Value": 241, "Color": "#ffd300", "Description": "Dbl Crop Corn/Soybeans"},
    {"Value": 242, "Color": "#000099", "Description": "Blueberries"},
    {"Value": 243, "Color": "#ff6666", "Description": "Cabbage"},
    {"Value": 244, "Color": "#ff6666", "Description": "Cauliflower"},
    {"Value": 245, "Color": "#ff6666", "Description": "Celery"},
    {"Value": 246, "Color": "#ff6666", "Description": "Radishes"},
    {"Value": 247, "Color": "#ff6666", "Description": "Turnips"},
    {"Value": 248, "Color": "#ff6666", "Description": "Eggplants"},
    {"Value": 249, "Color": "#ff6666", "Description": "Gourds"},
    {"Value": 250, "Color": "#ff6666", "Description": "Cranberries"},
    {"Value": 254, "Color": "#267000", "Description": "Dbl Crop Barley/Soybeans"}
]
